version: '3.7'

services:
    web:
        build:
          context: .
          dockerfile: Dockerfile-client
        image: bonds-client
        ports:
            - 3000:80
    back:
      build:
        context: .
        dockerfile: Dockerfile
      image: bonds
      ports:
        - 8080:8080

